CONTROL_CATALOG = {
    "AC-01": {
        "title": "MFA Enforcement",
        "domain": "Access Control",
        "frameworks": {
            "pci_dss": ["8.4"],
            "soc2": ["CC6.1"],
            "nist_800_53": ["IA-2"],
            "iso_27001": ["A.5.17"],
            "iso_27002": ["5.17"],
        },
        "required_collectors": ["auth_success", "auth_failure"],
        "supporting_collectors": ["ssh_config", "sudo_activity"],
        "documentation_sufficient": False,
    },
    "AC-02": {
        "title": "Centralized Identity and Access Management",
        "domain": "Access Control",
        "frameworks": {
            "pci_dss": ["7.2", "8.2"],
            "soc2": ["CC6.1", "CC6.3"],
            "nist_800_53": ["AC-2", "AC-3"],
            "iso_27001": ["A.5.15", "A.5.16"],
            "iso_27002": ["5.15", "5.16"],
        },
        "required_collectors": ["user_changes", "auth_success", "auth_failure"],
        "supporting_collectors": ["ssh_config", "sudo_activity"],
        "documentation_sufficient": False,
    },
    "AC-04": {
        "title": "Privileged Access Management",
        "domain": "Access Control",
        "frameworks": {
            "pci_dss": ["7.2", "8.2"],
            "soc2": ["CC6.1", "CC6.3"],
            "nist_800_53": ["AC-5", "AC-6"],
            "iso_27001": ["A.5.15", "A.5.18"],
            "iso_27002": ["5.15", "5.18"],
        },
        "required_collectors": ["sudo_activity", "user_changes"],
        "supporting_collectors": ["auth_success", "ssh_config"],
        "documentation_sufficient": False,
    },
    "AC-05": {
        "title": "User Access Provisioning",
        "domain": "Access Control",
        "frameworks": {
            "pci_dss": ["7.2"],
            "soc2": ["CC6.1"],
            "nist_800_53": ["AC-2"],
            "iso_27001": ["A.5.16"],
            "iso_27002": ["5.16"],
        },
        "required_collectors": ["user_changes"],
        "supporting_collectors": ["auth_success"],
        "documentation_sufficient": False,
    },
    "AC-06": {
        "title": "User Access Deprovisioning",
        "domain": "Access Control",
        "frameworks": {
            "pci_dss": ["7.2"],
            "soc2": ["CC6.1"],
            "nist_800_53": ["AC-2"],
            "iso_27001": ["A.5.16"],
            "iso_27002": ["5.16"],
        },
        "required_collectors": ["user_changes"],
        "supporting_collectors": ["auth_failure", "auth_success"],
        "documentation_sufficient": False,
    },
    "AC-07": {
        "title": "Periodic Access Reviews",
        "domain": "Access Control",
        "frameworks": {
            "pci_dss": ["7.2.4"],
            "soc2": ["CC6.1"],
            "nist_800_53": ["AC-2"],
            "iso_27001": ["A.5.18"],
            "iso_27002": ["5.18"],
        },
        "required_collectors": [],
        "supporting_collectors": ["user_changes"],
        "documentation_sufficient": True,
    },
    "AM-01": {
        "title": "Asset Inventory Management",
        "domain": "Asset Management",
        "frameworks": {
            "pci_dss": ["12.5"],
            "soc2": ["CC6.1", "CC8.1"],
            "nist_800_53": ["CM-8"],
            "iso_27001": ["A.5.9"],
            "iso_27002": ["5.9"],
        },
        "required_collectors": ["packages"],
        "supporting_collectors": ["docker_inventory", "open_ports"],
        "documentation_sufficient": True,
    },
    "AM-02": {
        "title": "Asset Ownership Assignment",
        "domain": "Asset Management",
        "frameworks": {
            "pci_dss": ["12.5"],
            "soc2": ["CC1.2", "CC6.1"],
            "nist_800_53": ["CM-8"],
            "iso_27001": ["A.5.9"],
            "iso_27002": ["5.9"],
        },
        "required_collectors": [],
        "supporting_collectors": [],
        "documentation_sufficient": True,
    },
    "AM-03": {
        "title": "System Classification and Data Sensitivity",
        "domain": "Asset Management",
        "frameworks": {
            "pci_dss": ["12.5"],
            "soc2": ["CC6.1"],
            "nist_800_53": ["RA-2"],
            "iso_27001": ["A.5.12", "A.5.13"],
            "iso_27002": ["5.12", "5.13"],
        },
        "required_collectors": [],
        "supporting_collectors": [],
        "documentation_sufficient": True,
    },
    "AM-04": {
        "title": "Software Inventory Management",
        "domain": "Asset Management",
        "frameworks": {
            "pci_dss": ["2.2", "6.3.3"],
            "soc2": ["CC8.1"],
            "nist_800_53": ["CM-8"],
            "iso_27001": ["A.8.9"],
            "iso_27002": ["8.9"],
        },
        "required_collectors": ["packages"],
        "supporting_collectors": ["docker_inventory"],
        "documentation_sufficient": False,
    },
    "CM-01": {
        "title": "Baseline Configuration Management",
        "domain": "Configuration Management",
        "frameworks": {
            "pci_dss": ["2.2"],
            "soc2": ["CC8.1"],
            "nist_800_53": ["CM-2", "CM-6"],
            "iso_27001": ["A.8.9"],
            "iso_27002": ["8.9"],
        },
        "required_collectors": ["ssh_config", "packages"],
        "supporting_collectors": ["docker_inventory"],
        "documentation_sufficient": False,
    },
    "CM-02": {
        "title": "Configuration Change Management",
        "domain": "Configuration Management",
        "frameworks": {
            "pci_dss": ["6.5", "6.5.1"],
            "soc2": ["CC8.1"],
            "nist_800_53": ["CM-3"],
            "iso_27001": ["A.8.32"],
            "iso_27002": ["8.32"],
        },
        "required_collectors": [],
        "supporting_collectors": ["packages", "docker_inventory"],
        "documentation_sufficient": True,
    },
    "CM-03": {
        "title": "Secure Configuration Review",
        "domain": "Configuration Management",
        "frameworks": {
            "pci_dss": ["2.2"],
            "soc2": ["CC8.1"],
            "nist_800_53": ["CM-6"],
            "iso_27001": ["A.8.9"],
            "iso_27002": ["8.9"],
        },
        "required_collectors": ["ssh_config"],
        "supporting_collectors": ["packages", "docker_inventory"],
        "documentation_sufficient": False,
    },
    "NS-01": {
        "title": "Network Security and Exposure Review",
        "domain": "Network Security",
        "frameworks": {
            "pci_dss": ["1.2", "1.3"],
            "soc2": ["CC6.6", "CC6.7"],
            "nist_800_53": ["SC-7"],
            "iso_27001": ["A.8.20"],
            "iso_27002": ["8.20"],
        },
        "required_collectors": ["open_ports", "listening_services", "firewall_status"],
        "supporting_collectors": [],
        "documentation_sufficient": False,
    },
    "SI-01": {
        "title": "Centralized Logging and Monitoring",
        "domain": "Logging and Monitoring",
        "frameworks": {
            "pci_dss": ["10.2", "10.4", "10.6"],
            "soc2": ["CC7.2", "CC7.3"],
            "nist_800_53": ["AU-6", "SI-4"],
            "iso_27001": ["A.8.15", "A.8.16", "A.8.17"],
            "iso_27002": ["8.15", "8.16", "8.17"],
        },
        "required_collectors": ["auth_success", "auth_failure", "sudo_activity", "time_sync"],
        "supporting_collectors": [],
        "documentation_sufficient": False,
    },
    "VM-01": {
        "title": "Vulnerability Management Program",
        "domain": "Vulnerability Management",
        "frameworks": {
            "pci_dss": ["6.3.3", "11.3.1", "11.3.2"],
            "soc2": ["CC7.1", "CC7.2"],
            "nist_800_53": ["RA-5", "SI-2"],
            "iso_27001": ["A.8.8"],
            "iso_27002": ["8.8"],
        },
        "required_collectors": ["packages", "available_updates"],
        "supporting_collectors": ["held_packages"],
        "documentation_sufficient": False,
    },
    "IR-01": {
        "title": "Incident Response Procedures",
        "domain": "Incident Response",
        "frameworks": {
            "pci_dss": ["12.10"],
            "soc2": ["CC7.4", "CC7.5"],
            "nist_800_53": ["IR-4"],
            "iso_27001": ["A.5.24", "A.5.25"],
            "iso_27002": ["5.24", "5.25"],
        },
        "required_collectors": [],
        "supporting_collectors": [],
        "documentation_sufficient": True,
    },
    "CP-01": {
        "title": "Backup, Recovery, and Continuity",
        "domain": "Continuity and Resilience",
        "frameworks": {
            "pci_dss": ["12.10"],
            "soc2": ["A1.2"],
            "nist_800_53": ["CP-9", "CP-10"],
            "iso_27001": ["A.5.30", "A.8.13"],
            "iso_27002": ["5.30", "8.13"],
        },
        "required_collectors": ["disk_usage"],
        "supporting_collectors": [],
        "documentation_sufficient": True,
    },
    "SD-01": {
        "title": "Secure Development and Deployment",
        "domain": "Secure Development",
        "frameworks": {
            "pci_dss": ["6.2", "6.5"],
            "soc2": ["CC8.1"],
            "nist_800_53": ["SA-10", "CM-3"],
            "iso_27001": ["A.8.25", "A.8.32"],
            "iso_27002": ["8.25", "8.32"],
        },
        "required_collectors": [],
        "supporting_collectors": ["docker_inventory", "packages"],
        "documentation_sufficient": True,
    },
}

CONTROL_STATUS_ORDER = {
    "missing": 0,
    "documented": 50,
    "partially_validated": 70,
    "validated": 100,
    "satisfied_by_documentation": 100,
    "continuous_monitoring": 100,
}
