from datetime import datetime, timezone
from app.services.remote_executor import run_ssh_command

PRIVILEGED_COMMAND = "sudo /usr/local/sbin/compliance-agent-command"


COLLECTORS = {'iam_users': {'command': f'{PRIVILEGED_COMMAND} collect-iam-users',
               'control_ids': ['AC-02', 'AC-01', 'AC-07'],
               'frameworks': {'pci_dss': ['7.2', '8.2', '8.3'],
                              'soc2': ['CC6.1', 'CC6.2'],
                              'nist_800_53': ['AC-2', 'IA-2', 'AC-6'],
                              'iso_27001': ['A.5.15', 'A.5.16', 'A.8.2'],
                              'iso_27002': ['5.15', '5.16', '8.2']}},
 'user_changes': {'command': f'{PRIVILEGED_COMMAND} collect-user-changes',
                  'control_ids': ['AC-02', 'SI-01'],
                  'frameworks': {'pci_dss': ['7.2', '8.2', '10.2'],
                                 'soc2': ['CC6.1', 'CC7.2'],
                                 'nist_800_53': ['AC-2', 'AU-6'],
                                 'iso_27001': ['A.5.15', 'A.8.15'],
                                 'iso_27002': ['5.15', '8.15']}},
 'auth_success': {'command': f'{PRIVILEGED_COMMAND} collect-auth-success',
                  'control_ids': ['AC-02', 'SI-01'],
                  'frameworks': {'pci_dss': ['8.2', '10.2'],
                                 'soc2': ['CC6.1', 'CC7.2'],
                                 'nist_800_53': ['AU-6', 'AC-2'],
                                 'iso_27001': ['A.8.15', 'A.8.16'],
                                 'iso_27002': ['8.15', '8.16']}},
 'auth_failure': {'command': f'{PRIVILEGED_COMMAND} collect-auth-failure',
                  'control_ids': ['AC-02', 'SI-01'],
                  'frameworks': {'pci_dss': ['8.2', '10.2', '10.6'],
                                 'soc2': ['CC6.1', 'CC7.2'],
                                 'nist_800_53': ['AU-6', 'SI-4'],
                                 'iso_27001': ['A.8.15', 'A.8.16'],
                                 'iso_27002': ['8.15', '8.16']}},
 'sudo_activity': {'command': f'{PRIVILEGED_COMMAND} collect-sudo-activity',
                   'control_ids': ['AC-02', 'SI-01'],
                   'frameworks': {'pci_dss': ['7.2', '10.2'],
                                  'soc2': ['CC6.1', 'CC7.2'],
                                  'nist_800_53': ['AC-6', 'AU-6'],
                                  'iso_27001': ['A.5.15', 'A.8.15'],
                                  'iso_27002': ['5.15', '8.15']}},
 'open_ports': {'command': 'ss -tulpn',
                'control_ids': ['NS-01', 'CM-01'],
                'frameworks': {'pci_dss': ['1.2', '2.2'],
                               'soc2': ['CC6.6'],
                               'nist_800_53': ['SC-7', 'CM-6'],
                               'iso_27001': ['A.8.20', 'A.8.9'],
                               'iso_27002': ['8.20', '8.9']}},
 'listening_services': {'command': 'ss -tulpn',
                        'control_ids': ['NS-01', 'CM-01'],
                        'frameworks': {'pci_dss': ['1.2', '2.2'],
                                       'soc2': ['CC6.6', 'CC8.1'],
                                       'nist_800_53': ['SC-7', 'CM-6'],
                                       'iso_27001': ['A.8.20', 'A.8.9'],
                                       'iso_27002': ['8.20', '8.9']}},
 'resource_usage': {'command': "printf 'CPU_CORES='; nproc; printf '\\nMEMORY='; free -m | awk '/Mem:/ {print $2}'; "
                               'printf \'\\nDISK_ALLOCATED_BYTES=\'; lsblk -b -d -n -o SIZE,TYPE | awk \'$2=="disk" '
                               "{sum += $1} END {print sum+0}'",
                    'control_ids': ['AM-01', 'SI-01'],
                    'frameworks': {'pci_dss': ['12.5'],
                                   'soc2': ['CC7.2'],
                                   'nist_800_53': ['CM-8', 'SI-4'],
                                   'iso_27001': ['A.5.9', 'A.8.16'],
                                   'iso_27002': ['5.9', '8.16']}},
 'os_inventory': {'command': f'{PRIVILEGED_COMMAND} collect-os-inventory',
                  'control_ids': ['AM-01', 'CM-01'],
                  'frameworks': {'pci_dss': ['12.5'],
                                 'soc2': ['CC6.1', 'CC8.1'],
                                 'nist_800_53': ['CM-8'],
                                 'iso_27001': ['A.5.9'],
                                 'iso_27002': ['5.9']}},
 'apt_policy': {'command': "apt-cache policy $(dpkg-query -W -f='${binary:Package} ' 2>/dev/null) 2>/dev/null | head "
                           '-20000',
                'control_ids': ['VM-01', 'AM-04'],
                'frameworks': {'pci_dss': ['6.3.3'],
                               'soc2': ['CC7.1', 'CC8.1'],
                               'nist_800_53': ['RA-5', 'CM-8'],
                               'iso_27001': ['A.8.8', 'A.8.9'],
                               'iso_27002': ['8.8', '8.9']}},
 'packages': {'command': 'dpkg -l',
              'control_ids': ['VM-01', 'CM-01'],
              'frameworks': {'pci_dss': ['6.3.3', '11.3.1'],
                             'soc2': ['CC7.1', 'CC8.1'],
                             'nist_800_53': ['RA-5', 'CM-8'],
                             'iso_27001': ['A.8.8', 'A.8.9'],
                             'iso_27002': ['8.8', '8.9']}},
 'held_packages': {'command': 'apt-mark showhold',
                   'control_ids': ['VM-01', 'CM-01'],
                   'frameworks': {'pci_dss': ['6.3.3'],
                                  'soc2': ['CC7.1'],
                                  'nist_800_53': ['SI-2', 'CM-6'],
                                  'iso_27001': ['A.8.8'],
                                  'iso_27002': ['8.8']}},
 'available_updates': {'command': 'apt list --upgradable',
                       'control_ids': ['VM-01'],
                       'frameworks': {'pci_dss': ['6.3.3', '11.3.1'],
                                      'soc2': ['CC7.1'],
                                      'nist_800_53': ['RA-5', 'SI-2'],
                                      'iso_27001': ['A.8.8'],
                                      'iso_27002': ['8.8']}},
 'firewall_status': {'command': f'{PRIVILEGED_COMMAND} collect-firewall-status',
                     'control_ids': ['NS-01'],
                     'frameworks': {'pci_dss': ['1.2', '1.3'],
                                    'soc2': ['CC6.6'],
                                    'nist_800_53': ['SC-7'],
                                    'iso_27001': ['A.8.20'],
                                    'iso_27002': ['8.20']}},
 'ssh_config': {'command': f'{PRIVILEGED_COMMAND} collect-ssh-config',
                'control_ids': ['AC-02', 'CM-01'],
                'frameworks': {'pci_dss': ['2.2', '8.2'],
                               'soc2': ['CC6.1', 'CC8.1'],
                               'nist_800_53': ['AC-2', 'CM-6'],
                               'iso_27001': ['A.5.15', 'A.8.9'],
                               'iso_27002': ['5.15', '8.9']}},
 'time_sync': {'command': 'timedatectl',
               'control_ids': ['SI-01', 'CM-01'],
               'frameworks': {'pci_dss': ['10.4'],
                              'soc2': ['CC7.2'],
                              'nist_800_53': ['AU-8'],
                              'iso_27001': ['A.8.17'],
                              'iso_27002': ['8.17']}},
 'disk_usage': {'command': f'{PRIVILEGED_COMMAND} collect-disk-usage',
                'control_ids': ['CP-01', 'CM-01'],
                'frameworks': {'pci_dss': ['12.10.1'],
                               'soc2': ['A1.2'],
                               'nist_800_53': ['CP-9'],
                               'iso_27001': ['A.8.13'],
                               'iso_27002': ['8.13']}},
 'docker_inventory': {'command': f'{PRIVILEGED_COMMAND} collect-docker-inventory',
                      'control_ids': ['CM-01', 'VM-01'],
                      'frameworks': {'pci_dss': ['2.2', '6.3.3'],
                                     'soc2': ['CC7.1', 'CC8.1'],
                                     'nist_800_53': ['CM-8', 'RA-5'],
                                     'iso_27001': ['A.8.8', 'A.8.9'],
                                     'iso_27002': ['8.8', '8.9']}},
 'duo_mfa_linux': {'command': "if [ -f /etc/pam.d/sshd ] && grep -qi duo /etc/pam.d/sshd; then echo 'DUO_MFA_PRESENT'; "
                              "else echo 'DUO_MFA_NOT_PRESENT'; fi",
                   'control_ids': ['AC-01'],
                   'frameworks': {'pci_dss': ['8.4'],
                                  'soc2': ['CC6.1'],
                                  'nist_800_53': ['IA-2'],
                                  'iso_27001': ['A.5.17'],
                                  'iso_27002': ['5.17']}},
 'automox_amagent': {'command': 'if systemctl list-units --type=service --all | grep -qi amagent; then echo '
                                "'AUTOMOX_PRESENT'; else echo 'AUTOMOX_NOT_PRESENT'; fi",
                     'control_ids': ['VM-02'],
                     'frameworks': {'pci_dss': ['6.3.3'],
                                    'soc2': ['CC7.1'],
                                    'nist_800_53': ['SI-2'],
                                    'iso_27001': ['A.8.8'],
                                    'iso_27002': ['8.8']}},
 'trend_micro_ds_agent': {'command': "if systemctl list-units --type=service --all | grep -Eqi 'ds_agent|trend'; then "
                                     "echo 'TREND_MICRO_PRESENT'; else echo 'TREND_MICRO_NOT_PRESENT'; fi",
                          'control_ids': ['SI-03'],
                          'frameworks': {'pci_dss': ['5.2'],
                                         'soc2': ['CC7.2'],
                                         'nist_800_53': ['SI-3'],
                                         'iso_27001': ['A.8.7'],
                                         'iso_27002': ['8.7']}},
 'listening_ports': {'control_ids': ['CM-01'],
                     'frameworks': ['pci_dss', 'soc2', 'nist_800_53', 'iso_27002'],
                     'command': f'{PRIVILEGED_COMMAND} collect-listening-ports'},
 'package_inventory': {'control_ids': ['CM-01'],
                       'frameworks': ['pci_dss', 'soc2', 'nist_800_53', 'iso_27002'],
                       'command': f'{PRIVILEGED_COMMAND} collect-package-inventory'},
 'agent_lifecycle': {'control_ids': ['CM-01'],
                     'frameworks': ['pci_dss', 'soc2', 'nist_800_53', 'iso_27001', 'iso_27002'],
                     'command': f'{PRIVILEGED_COMMAND} collect-agent-lifecycle'},
 'collector_health': {'control_ids': ['CM-01'],
                      'frameworks': ['pci_dss', 'soc2', 'nist_800_53', 'iso_27001', 'iso_27002'],
                      'command': f'{PRIVILEGED_COMMAND} collect-collector-health'}}


def run_collector(asset, collector_name: str) -> dict:
    if collector_name not in COLLECTORS:
        return {"collector": collector_name, "status": "failed", "error": "Unknown collector"}

    if (getattr(asset, "os_family", "") or "").strip().lower() == "windows":
        return {
            "collector": collector_name,
            "asset_id": asset.asset_id,
            "collected_at": datetime.now(timezone.utc).isoformat(),
            "status": "skipped",
            "stderr": (
                "Linux SSH collectors are not supported for Windows assets; "
                "use the Windows agent collector payload."
            ),
        }

    spec = COLLECTORS[collector_name]
    result = run_ssh_command(host=asset.address, username=asset.ssh_user, command=spec["command"], timeout=120, port=asset.ssh_port or 22)

    return {
        "collector": collector_name,
        "asset_id": asset.asset_id,
        "collected_at": datetime.now(timezone.utc).isoformat(),
        "command": spec["command"],
        "control_ids": spec["control_ids"],
        "frameworks": spec["frameworks"],
        "stdout": result.get("stdout", ""),
        "stderr": result.get("stderr", ""),
        "exit_code": result.get("exit_code"),
        "status": (
           "completed"
           if result.get("exit_code") == 0
           and "NOT_PRESENT" not in result.get("stdout", "")
           else "failed"
         )
    }
